name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Analyze
      uses: dgmjr-actions/build-using-dgmjrsdk@main
      with:
        git-token: ${{ secrets.GITHUB_TOKEN }}
        configuration: Release
        git-nuget-endpoint: ${{ vars.GIT_NUGET_ENDPOINT }}
        private-nuget-endpoint: ${{ vars.PROGET_ENDPOINT_URL }}
        private-nuget-api-key: ${{ secrets.PROGET_API_KEY }}
        repo: dgmjr-io/Dgmjr.ComponentModel
        project-file-path: Dgmjr.ComponentModel.csproj
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    - name: End Sonar Scanner
      shell: pwsh
      run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
